---

basic_images:
    pause-amd64:
        name: mirrorgooglecontainers/pause-amd64:3.0
        target: gcr.io/google_containers/pause-amd64:3.0
    flannel:
        name: jmgao1983/flannel:v0.10.0-amd64
        target: quay.io/coreos/flannel:v0.10.0-amd64
    k8s-dns-kube-dns-amd64:
        name: nuaays/k8s-dns-kube-dns-amd64:1.14.8
        target: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.8
    k8s-dns-dnsmasq-nanny-amd64:
        name: nuaays/k8s-dns-dnsmasq-nanny-amd64:1.14.8
        target: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.8
    k8s-dns-sidecar-amd64:
        name: nuaays/k8s-dns-sidecar-amd64:1.14.8
        target: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.8
    dashboard:
        name: mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.6.3
        target: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
    heapster-grafana:
        name: mirrorgooglecontainers/heapster-grafana-amd64:v4.4.3
        target: gcr.io/google_containers/heapster-grafana-amd64:v4.4.3
    heapster-amd64:
        name: mirrorgooglecontainers/heapster-amd64:v1.5.1
        target: gcr.io/google_containers/heapster-amd64:v1.5.1
    heapster-influxdb:
        name: mirrorgooglecontainers/heapster-influxdb-amd64:v1.3.3
        target: gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3

